// Generated by tools/generate-contract-routes.mjs — do not edit by hand.
//
// The routes the oRPC client needs, without the schemas it never runs.
// Typed as the real contract, so every call site keeps the types the
// contract defines; the import below is type-only and erased at build.

import type * as shared from '@b2b-catalog-platform/shared';

export const accountContract = {
  getProfile: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: { method: 'GET', path: '/account/profile' },
    },
  },
  updateProfile: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'PATCH',
        path: '/account/profile',
        inputStructure: 'detailed',
      },
    },
  },
  deleteAccount: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'POST',
        path: '/account/delete',
        inputStructure: 'detailed',
      },
    },
  },
} as unknown as typeof shared.accountContract;
export const addressSuggestionContract = {
  suggestAddresses: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'GET',
        path: '/addresses/suggestions',
        inputStructure: 'detailed',
      },
    },
  },
} as unknown as typeof shared.addressSuggestionContract;
export const addressesContract = {
  listAddresses: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: { method: 'GET', path: '/account/addresses' },
    },
  },
  createAddress: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'POST',
        path: '/account/addresses',
        inputStructure: 'detailed',
      },
    },
  },
  updateAddress: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'PUT',
        path: '/account/addresses/{id}',
        inputStructure: 'detailed',
      },
    },
  },
  deleteAddress: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'DELETE',
        path: '/account/addresses/{id}',
        inputStructure: 'detailed',
      },
    },
  },
} as unknown as typeof shared.addressesContract;
export const adminCatalogContract = {
  listProducts: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'GET',
        path: '/admin/catalog/products',
        inputStructure: 'detailed',
      },
    },
  },
  getProduct: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'GET',
        path: '/admin/catalog/products/{slug}',
        inputStructure: 'detailed',
      },
    },
  },
  createProduct: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'POST',
        path: '/admin/catalog/products',
        inputStructure: 'detailed',
      },
    },
  },
  updateProduct: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'PUT',
        path: '/admin/catalog/products/{slug}',
        inputStructure: 'detailed',
      },
    },
  },
  deleteProduct: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'DELETE',
        path: '/admin/catalog/products/{slug}',
        inputStructure: 'detailed',
      },
    },
  },
  restoreProduct: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'POST',
        path: '/admin/catalog/products/{slug}/restore',
        inputStructure: 'detailed',
      },
    },
  },
  setProductPublished: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'PATCH',
        path: '/admin/catalog/products/{slug}/published',
        inputStructure: 'detailed',
      },
    },
  },
  listHiddenProducts: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'GET',
        path: '/admin/catalog/categories/{slug}/hidden-products',
        inputStructure: 'detailed',
      },
    },
  },
  listCategories: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: { method: 'GET', path: '/admin/catalog/categories' },
    },
  },
  createCategory: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'POST',
        path: '/admin/catalog/categories',
        inputStructure: 'detailed',
      },
    },
  },
  updateCategory: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'PUT',
        path: '/admin/catalog/categories/{id}',
        inputStructure: 'detailed',
      },
    },
  },
  deleteCategory: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'DELETE',
        path: '/admin/catalog/categories/{id}',
        inputStructure: 'detailed',
      },
    },
  },
  reorderCategories: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'PATCH',
        path: '/admin/catalog/categories/order',
        inputStructure: 'detailed',
      },
    },
  },
} as unknown as typeof shared.adminCatalogContract;
export const attributesContract = {
  listAttributes: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: { method: 'GET', path: '/admin/attributes' },
    },
  },
  listAttributeKeys: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: { method: 'GET', path: '/admin/attributes/inventory' },
    },
  },
  listAttributeValues: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'GET',
        path: '/admin/attributes/inventory/values',
        inputStructure: 'detailed',
      },
    },
  },
  renameAttributeKey: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'POST',
        path: '/admin/attributes/inventory/rename-key',
        inputStructure: 'detailed',
      },
    },
  },
  renameAttributeValue: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'POST',
        path: '/admin/attributes/inventory/rename-value',
        inputStructure: 'detailed',
      },
    },
  },
  createAttribute: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'POST',
        path: '/admin/attributes',
        inputStructure: 'detailed',
      },
    },
  },
  updateAttribute: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'PUT',
        path: '/admin/attributes/{id}',
        inputStructure: 'detailed',
      },
    },
  },
  reorderAttributes: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'PATCH',
        path: '/admin/attributes/order',
        inputStructure: 'detailed',
      },
    },
  },
  getCategoryFilters: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'GET',
        path: '/admin/categories/{slug}/filters',
        inputStructure: 'detailed',
      },
    },
  },
  saveCategoryFilters: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'PUT',
        path: '/admin/categories/{slug}/filters',
        inputStructure: 'detailed',
      },
    },
  },
  resetCategoryFilters: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'DELETE',
        path: '/admin/categories/{slug}/filters',
        inputStructure: 'detailed',
      },
    },
  },
  deleteAttribute: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'DELETE',
        path: '/admin/attributes/{id}',
        inputStructure: 'detailed',
      },
    },
  },
} as unknown as typeof shared.attributesContract;
export const authContract = {
  register: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'POST',
        path: '/auth/register',
        inputStructure: 'detailed',
      },
    },
  },
  forgotPassword: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'POST',
        path: '/auth/forgot-password',
        inputStructure: 'detailed',
      },
    },
  },
  checkPasswordToken: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'GET',
        path: '/auth/password-token/{token}',
        inputStructure: 'detailed',
      },
    },
  },
  setPassword: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'POST',
        path: '/auth/set-password',
        inputStructure: 'detailed',
      },
    },
  },
  login: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'POST',
        path: '/auth/login',
        inputStructure: 'detailed',
      },
    },
  },
  logout: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: { method: 'POST', path: '/auth/logout' },
    },
  },
  me: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: { method: 'GET', path: '/auth/me' },
    },
  },
  changePassword: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'POST',
        path: '/auth/change-password',
        inputStructure: 'detailed',
      },
    },
  },
} as unknown as typeof shared.authContract;
export const cartContract = {
  previewCart: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'POST',
        path: '/cart/preview',
        inputStructure: 'detailed',
      },
    },
  },
} as unknown as typeof shared.cartContract;
export const catalogContract = {
  getCategoryTree: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: { method: 'GET', path: '/catalog/categories' },
    },
  },
  getCategoryProducts: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'GET',
        path: '/catalog/categories/{slug}/products',
        inputStructure: 'detailed',
      },
    },
  },
  searchProducts: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'GET',
        path: '/catalog/search',
        inputStructure: 'detailed',
      },
    },
  },
  getSearchSuggestions: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'GET',
        path: '/catalog/search/suggestions',
        inputStructure: 'detailed',
      },
    },
  },
  getSitemap: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: { method: 'GET', path: '/catalog/sitemap' },
    },
  },
  getProduct: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'GET',
        path: '/catalog/products/{slug}',
        inputStructure: 'detailed',
      },
    },
  },
} as unknown as typeof shared.catalogContract;
export const inquiryContract = {
  submit: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: { method: 'POST', path: '/inquiry', inputStructure: 'detailed' },
    },
  },
} as unknown as typeof shared.inquiryContract;
export const ordersContract = {
  submitOrder: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: { method: 'POST', path: '/orders', inputStructure: 'detailed' },
    },
  },
  listMyOrders: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'GET',
        path: '/account/orders',
        inputStructure: 'detailed',
      },
    },
  },
  getMyOrder: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'GET',
        path: '/account/orders/{reference}',
        inputStructure: 'detailed',
      },
    },
  },
  getOrderByToken: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'GET',
        path: '/orders/by-token/{token}',
        inputStructure: 'detailed',
      },
    },
  },
  listOrders: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'GET',
        path: '/admin/orders',
        inputStructure: 'detailed',
      },
    },
  },
  getOrder: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'GET',
        path: '/admin/orders/{reference}',
        inputStructure: 'detailed',
      },
    },
  },
} as unknown as typeof shared.ordersContract;
export const pageContract = {
  getPage: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'GET',
        path: '/pages/{slug}',
        inputStructure: 'detailed',
      },
    },
  },
  updatePage: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'PUT',
        path: '/pages/{slug}',
        inputStructure: 'detailed',
      },
    },
  },
} as unknown as typeof shared.pageContract;
export const partySuggestionContract = {
  suggestParties: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'GET',
        path: '/companies/suggestions',
        inputStructure: 'detailed',
      },
    },
  },
} as unknown as typeof shared.partySuggestionContract;
export const settingsContract = {
  checkMaintenance: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: { method: 'GET', path: '/maintenance' },
    },
  },
  getBuildInfo: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: { method: 'GET', path: '/settings/build-info' },
    },
  },
  getMaintenance: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: { method: 'GET', path: '/settings/maintenance' },
    },
  },
  setMaintenance: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'PUT',
        path: '/settings/maintenance',
        inputStructure: 'detailed',
      },
    },
  },
} as unknown as typeof shared.settingsContract;
export const syncContract = {
  commitRun: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'POST',
        path: '/admin/sync/runs/{id}/commit',
        inputStructure: 'detailed',
      },
    },
  },
  getRun: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'GET',
        path: '/admin/sync/runs/{id}',
        inputStructure: 'detailed',
      },
    },
  },
  listRuns: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'GET',
        path: '/admin/sync/runs',
        inputStructure: 'detailed',
      },
    },
  },
} as unknown as typeof shared.syncContract;
export const tiersContract = {
  listTiers: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: { method: 'GET', path: '/admin/tiers' },
    },
  },
  createTier: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'POST',
        path: '/admin/tiers',
        inputStructure: 'detailed',
      },
    },
  },
  updateTier: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'PUT',
        path: '/admin/tiers/{id}',
        inputStructure: 'detailed',
      },
    },
  },
  reorderTiers: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'PATCH',
        path: '/admin/tiers/order',
        inputStructure: 'detailed',
      },
    },
  },
  deleteTier: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'DELETE',
        path: '/admin/tiers/{id}',
        inputStructure: 'detailed',
      },
    },
  },
} as unknown as typeof shared.tiersContract;
export const usersContract = {
  listUsers: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'GET',
        path: '/admin/users',
        inputStructure: 'detailed',
      },
    },
  },
  approveUser: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'POST',
        path: '/admin/users/{id}/approve',
        inputStructure: 'detailed',
      },
    },
  },
  createUser: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'POST',
        path: '/admin/users',
        inputStructure: 'detailed',
      },
    },
  },
  getUser: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'GET',
        path: '/admin/users/{id}',
        inputStructure: 'detailed',
      },
    },
  },
  updateUser: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'PATCH',
        path: '/admin/users/{id}',
        inputStructure: 'detailed',
      },
    },
  },
  setUserActive: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'PATCH',
        path: '/admin/users/{id}/active',
        inputStructure: 'detailed',
      },
    },
  },
  resendInvitation: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'POST',
        path: '/admin/users/{id}/invite',
        inputStructure: 'detailed',
      },
    },
  },
  deleteUser: {
    '~orpc': {
      errorMap: {},
      meta: {},
      route: {
        method: 'DELETE',
        path: '/admin/users/{id}',
        inputStructure: 'detailed',
      },
    },
  },
} as unknown as typeof shared.usersContract;
